export type DefaultSwiftFormatArguments = Map<SwiftFormatArgumentsKey, string>;
export type SwiftFormatArguments = Map<
  SwiftFormatArgumentsKey,
  string | undefined
>;

export interface SwiftFormatConfig {
  options: Record<string, string>;
  enabled: Record<string, boolean>;
}

export type SwiftFormatArgumentsKey =
  typeof validSwiftFormatArgumentsKeys[number];

export const validSwiftFormatArgumentsKeys = [
  "acronyms",
  "allman",
  "anonymousforeach",
  "assetliterals",
  "asynccapturing",
  "beforemarks",
  "binarygrouping",
  "callsiteparen",
  "categorymark",
  "classthreshold",
  "closingparen",
  "closurevoid",
  "commas",
  "complexattrs",
  "computedvarattrs",
  "condassignment",
  "conflictmarkers", // Added manually
  "dateformat",
  "decimalgrouping",
  "doccomments",
  "elseposition",
  "emptybraces",
  "enumnamespaces",
  "enumthreshold",
  "exponentcase",
  "exponentgrouping",
  "extensionacl",
  "extensionlength",
  "extensionmark",
  "fractiongrouping",
  "fragment", // Added manually
  "funcattributes",
  "generictypes",
  "groupedextension",
  "guardelse",
  "header",
  "hexgrouping",
  "hexliteralcase",
  "ifdef",
  "importgrouping",
  "indent",
  "indentcase",
  "indentstrings",
  "initcodernil",
  "lifecycle",
  "lineaftermarks",
  "linebreaks",
  "markcategories",
  "markextensions",
  "marktypes",
  "maxwidth",
  "modifierorder",
  "nevertrailing",
  "nilinit",
  "noncomplexattrs",
  "nospaceoperators",
  "nowrapoperators",
  "octalgrouping",
  "onelineforeach",
  "operatorfunc",
  "organizationmode",
  "organizetypes",
  "patternlet",
  "ranges",
  "redundanttype",
  "self",
  "selfrequired",
  "semicolons",
  "shortoptionals",
  "smarttabs",
  "someany",
  "storedvarattrs",
  "stripunusedargs",
  "structthreshold",
  "tabwidth",
  "throwcapturing",
  "timezone",
  "trailingclosures",
  "trimwhitespace",
  "typeattributes",
  "typeblanklines",
  "typedelimiter",
  "typemark",
  "voidtype",
  "wraparguments",
  "wrapcollections",
  "wrapconditions",
  "wrapeffects",
  "wrapenumcases",
  "wrapparameters",
  "wrapreturntype",
  "wrapternary",
  "wraptypealiases",
  "xcodeindentation",
  "yodaswap",
  "enable",
  "disable",
] as const;
